version: "3.8"
# https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
      - ./ovpn-data:/etc/openvpn
